export const HA_TOOLBOX = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: 'Automatisierung',
      colour: '#5C6BC0',
      contents: [{ kind: 'block', type: 'ha_automation' }],
    },
    {
      kind: 'category',
      name: 'Trigger',
      colour: '#FF6680',
      contents: [
        { kind: 'block', type: 'ha_time_trigger' },
        { kind: 'block', type: 'ha_datetime_trigger' },
        { kind: 'block', type: 'ha_calendar_trigger' },
        { kind: 'block', type: 'ha_state_trigger' },
        { kind: 'block', type: 'ha_numeric_state_trigger' },
        { kind: 'block', type: 'ha_event_trigger' },
        { kind: 'block', type: 'ha_webhook_trigger' },
        { kind: 'block', type: 'ha_sun_trigger' },
        { kind: 'block', type: 'ha_template_trigger' },
        { kind: 'block', type: 'ha_homeassistant_trigger' },
      ],
    },
    {
      kind: 'category',
      name: 'Logik',
      colour: '#43A047',
      contents: [
        { kind: 'block', type: 'ha_if_logic' },
        { kind: 'block', type: 'ha_compare' },
        { kind: 'block', type: 'ha_logic_op' },
        { kind: 'block', type: 'ha_logic_not' },
        { kind: 'block', type: 'ha_boolean' },
        { kind: 'block', type: 'ha_logic_ternary' },
        { kind: 'block', type: 'ha_if_boolean' },
        { kind: 'block', type: 'ha_if_and' },
        { kind: 'block', type: 'ha_if_or' },
        { kind: 'block', type: 'ha_if_not' },
      ],
    },
    {
      kind: 'category',
      name: 'Mathematik',
      colour: '#5C6BC0',
      contents: [
        { kind: 'block', type: 'ha_number' },
        { kind: 'block', type: 'ha_math' },
        { kind: 'block', type: 'ha_to_number' },
      ],
    },
    {
      kind: 'category',
      name: 'Text',
      colour: '#C0CA33',
      contents: [
        { kind: 'block', type: 'ha_text' },
        {
          kind: 'block',
          type: 'ha_text_join',
          extraState: { itemCount: 2 },
          fields: { SEP: 'space' },
          inputs: {
            ADD0: { shadow: { type: 'ha_text', fields: { TEXT: '' } } },
            ADD1: { shadow: { type: 'ha_text', fields: { TEXT: '' } } },
          },
        },
        { kind: 'block', type: 'ha_text_labeled' },
        { kind: 'block', type: 'ha_text_length' },
        { kind: 'block', type: 'ha_text_contains' },
        { kind: 'block', type: 'ha_text_is_empty' },
        { kind: 'block', type: 'ha_entity_state' },
        { kind: 'block', type: 'ha_entity_attribute' },
        { kind: 'block', type: 'ha_variable_get' },
      ],
    },
    {
      kind: 'category',
      name: 'Bedingungen',
      colour: '#F9A825',
      contents: [
        { kind: 'block', type: 'ha_if_state' },
        { kind: 'block', type: 'ha_if_numeric_state' },
        { kind: 'block', type: 'ha_if_time' },
        { kind: 'block', type: 'ha_if_date' },
        { kind: 'block', type: 'ha_if_sun' },
        { kind: 'block', type: 'ha_if_present' },
        { kind: 'block', type: 'ha_if_zone' },
        { kind: 'block', type: 'ha_if_not_remembered' },
        { kind: 'block', type: 'ha_if_template' },
      ],
    },
    {
      kind: 'category',
      name: 'Aktionen',
      colour: '#26A69A',
      contents: [
        { kind: 'block', type: 'ha_call_service' },
        { kind: 'block', type: 'ha_activate_scene' },
        { kind: 'block', type: 'ha_notify' },
        { kind: 'block', type: 'ha_notify_telegram' },
        { kind: 'block', type: 'ha_alexa_speak' },
        { kind: 'block', type: 'ha_remember' },
        { kind: 'block', type: 'ha_delay' },
        { kind: 'block', type: 'ha_wait_for_state' },
        { kind: 'block', type: 'ha_wait_for_template' },
        { kind: 'block', type: 'ha_repeat' },
        { kind: 'block', type: 'ha_repeat_while' },
        { kind: 'block', type: 'ha_if_else' },
        { kind: 'block', type: 'ha_stop' },
        { kind: 'block', type: 'ha_set_variable' },
      ],
    },
    {
      kind: 'category',
      name: 'Geräte',
      colour: '#FB8C00',
      contents: [
        { kind: 'block', type: 'ha_light_on' },
        { kind: 'block', type: 'ha_light_off' },
        { kind: 'block', type: 'ha_switch_toggle' },
        { kind: 'block', type: 'ha_send_push' },
      ],
    },
  ],
};
