/**
 * JSON-Blockdefinitionen nach der aktuellen Google-Blockly-API.
 * Verbindungen spiegeln das Home-Assistant-Modell: Trigger, Bedingungen, Aktionen.
 */
export const HA_BLOCK_DEFINITIONS: Array<Record<string, unknown>> = [
  {
    type: 'ha_automation',
    message0: 'Automatisierung',
    message1: 'Trigger %1',
    args1: [{ type: 'input_statement', name: 'TRIGGERS', check: 'Trigger' }],
    message2: 'Bedingungen %1',
    args2: [{ type: 'input_statement', name: 'CONDITIONS', check: 'Condition' }],
    message3: 'Aktionen %1',
    args3: [{ type: 'input_statement', name: 'ACTIONS', check: 'Action' }],
    colour: 230,
    tooltip: 'Wurzelblock einer Home-Assistant-Automatisierung.',
    helpUrl: 'https://www.home-assistant.io/docs/automation/',
  },
  {
    type: 'ha_time_trigger',
    message0: 'Wenn Zeit ist %1',
    args0: [{ type: 'field_time', name: 'TIME', value: '07:00' }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst zu einer bestimmten Uhrzeit aus.',
  },
  {
    type: 'ha_datetime_trigger',
    message0: 'Wenn Datum/Uhrzeit %1',
    args0: [{ type: 'field_datetime', name: 'DATETIME', value: '' }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst einmalig zu einem bestimmten Datum und einer Uhrzeit aus.',
  },
  {
    type: 'ha_calendar_trigger',
    message0: 'Wenn Kalender %1 %2',
    args0: [
      { type: 'field_entity', name: 'ENTITY_ID', value: '', domain: 'calendar' },
      {
        type: 'field_dropdown',
        name: 'CALENDAR_EVENT',
        options: [
          ['beginnt', 'start'],
          ['endet', 'end'],
        ],
      },
    ],
    message1: 'Offset (optional) %1',
    args1: [{ type: 'field_duration', name: 'OFFSET', value: '', allowNegative: true }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst bei Beginn oder Ende eines Kalendertermins aus.',
  },
  {
    type: 'ha_state_trigger',
    message0: 'Wenn Zustand von %1 von %2 nach %3',
    args0: [
      { type: 'field_entity', name: 'ENTITY_ID', value: '' },
      { type: 'field_state', name: 'FROM', value: '' },
      { type: 'field_state', name: 'TO', value: 'on' },
    ],
    message1: 'für (optional) %1',
    args1: [{ type: 'field_duration', name: 'FOR', value: '' }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst bei einer Statusänderung aus.',
  },
  {
    type: 'ha_numeric_state_trigger',
    message0: 'Wenn numerischer Zustand von %1 über %2 unter %3',
    args0: [
      { type: 'field_entity', name: 'ENTITY_ID', value: '' },
      { type: 'field_optional_number', name: 'ABOVE', value: '20' },
      { type: 'field_optional_number', name: 'BELOW', value: '' },
    ],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst aus, wenn ein numerischer Wert eine Schwelle über- oder unterschreitet.',
  },
  {
    type: 'ha_event_trigger',
    message0: 'Wenn Ereignis %1',
    args0: [{ type: 'field_event_type', name: 'EVENT_TYPE', value: 'state_changed' }],
    message1: 'Event-Daten (optional, JSON) %1',
    args1: [{ type: 'field_input', name: 'EVENT_DATA', text: '' }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst bei einem Home-Assistant-Ereignis aus.',
  },
  {
    type: 'ha_webhook_trigger',
    message0: 'Wenn Webhook empfangen %1',
    args0: [{ type: 'field_input', name: 'WEBHOOK_ID', text: 'meine_webhook_id' }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst bei Aufruf eines Webhooks aus.',
  },
  {
    type: 'ha_sun_trigger',
    message0: 'Wenn Sonne %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'SUN_EVENT',
        options: [
          ['aufgeht', 'sunrise'],
          ['untergeht', 'sunset'],
        ],
      },
    ],
    message1: 'Offset (optional) %1',
    args1: [{ type: 'field_duration', name: 'OFFSET', value: '', allowNegative: true }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst bei Sonnenaufgang oder Sonnenuntergang aus.',
  },
  {
    type: 'ha_template_trigger',
    message0: 'Wenn Template wahr wird %1',
    args0: [{ type: 'field_input', name: 'TEMPLATE', text: "{{ states('sensor.temp') | float > 20 }}" }],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst aus, wenn ein Template wahr wird.',
  },
  {
    type: 'ha_homeassistant_trigger',
    message0: 'Wenn Home Assistant %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'EVENT',
        options: [
          ['startet', 'start'],
          ['herunterfährt', 'shutdown'],
        ],
      },
    ],
    previousStatement: 'Trigger',
    nextStatement: 'Trigger',
    colour: 210,
    tooltip: 'Löst beim Start oder Herunterfahren von Home Assistant aus.',
  },
  {
    type: 'ha_if_state',
    message0: 'Zustand von %1 ist %2',
    args0: [
      { type: 'field_entity', name: 'ENTITY_ID', value: '' },
      { type: 'field_state', name: 'STATE', value: 'on' },
    ],
    message1: 'für (optional) %1',
    args1: [{ type: 'field_duration', name: 'FOR', value: '' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft den Zustand einer Entität.',
  },
  {
    type: 'ha_if_numeric_state',
    message0: 'Numerischer Zustand von %1 über %2 unter %3',
    args0: [
      { type: 'field_entity', name: 'ENTITY_ID', value: '' },
      { type: 'field_optional_number', name: 'ABOVE', value: '20' },
      { type: 'field_optional_number', name: 'BELOW', value: '' },
    ],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft einen numerischen Zustand.',
  },
  {
    type: 'ha_if_time',
    message0: 'Zeit nach %1 und vor %2',
    args0: [
      { type: 'field_time', name: 'AFTER', value: '06:00' },
      { type: 'field_time', name: 'BEFORE', value: '22:00' },
    ],
    message1: 'an Wochentagen %1',
    args1: [{ type: 'field_weekdays', name: 'WEEKDAYS', value: '' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft die aktuelle Uhrzeit.',
  },
  {
    type: 'ha_if_date',
    message0: 'Datum ist %1',
    args0: [{ type: 'field_date', name: 'DATE', value: '' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft das aktuelle Datum.',
  },
  {
    type: 'ha_if_sun',
    message0: 'Sonne ist %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'SUN_STATE',
        options: [
          ['aufgegangen', 'above_horizon'],
          ['untergegangen', 'below_horizon'],
        ],
      },
    ],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft den Sonnenstand.',
  },
  {
    type: 'ha_if_template',
    message0: 'Template-Bedingung %1',
    args0: [{ type: 'field_input', name: 'TEMPLATE', text: "{{ is_state('sun.sun', 'above_horizon') }}" }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft ein Template.',
  },
  {
    type: 'ha_if_and',
    message0: 'alle Bedingungen (UND) %1',
    args0: [{ type: 'input_statement', name: 'CONDITIONS', check: 'Condition' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 120,
    tooltip: 'UND-Verknüpfung von Bedingungen.',
  },
  {
    type: 'ha_if_or',
    message0: 'eine Bedingung (ODER) %1',
    args0: [{ type: 'input_statement', name: 'CONDITIONS', check: 'Condition' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 120,
    tooltip: 'ODER-Verknüpfung von Bedingungen.',
  },
  {
    type: 'ha_if_not',
    message0: 'NICHT %1',
    args0: [{ type: 'input_statement', name: 'CONDITION', check: 'Condition' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 120,
    tooltip: 'Negiert eine Bedingung.',
  },
  {
    type: 'ha_call_service',
    message0: 'Service aufrufen %1',
    args0: [{ type: 'field_service', name: 'SERVICE', value: '' }],
    message1: 'Ziel %1',
    args1: [{ type: 'field_entity', name: 'ENTITY_ID', value: '' }],
    message2: 'Daten (optional, JSON) %1',
    args2: [{ type: 'field_input', name: 'SERVICE_DATA', text: '' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 160,
    tooltip: 'Ruft einen Home-Assistant-Service auf.',
  },
  {
    type: 'ha_activate_scene',
    message0: 'Szene aktivieren %1',
    args0: [{ type: 'field_entity', name: 'SCENE_ID', value: '', domain: 'scene' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 160,
    tooltip: 'Aktiviert eine Szene.',
  },
  {
    type: 'ha_notify',
    message0: 'Benachrichtigung senden an %1',
    args0: [{ type: 'field_notify_target', name: 'NOTIFY_SERVICE', value: '' }],
    message1: 'Nachricht %1',
    args1: [{ type: 'field_input', name: 'MESSAGE', text: 'Tür wurde geöffnet!' }],
    message2: 'Titel (optional) %1',
    args2: [{ type: 'field_input', name: 'TITLE', text: '' }],
    message3: 'oder Textbaustein %1',
    args3: [{ type: 'input_value', name: 'MESSAGE_VALUE', check: 'Text' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 160,
    tooltip: 'Sendet eine Push-Nachricht an ein Smartphone mit Home Assistant Companion App. Die Nachricht kann ein Textbaustein sein.',
  },
  {
    type: 'ha_text',
    message0: 'Text %1',
    args0: [{ type: 'field_input', name: 'TEXT', text: '' }],
    output: 'Text',
    colour: 65,
    tooltip: 'Ein fester Text, der mit Entitäten und Variablen verknüpft werden kann.',
  },
  {
    type: 'ha_text_labeled',
    message0: '%1: %2',
    args0: [
      { type: 'field_input', name: 'LABEL', text: 'Ort' },
      { type: 'input_value', name: 'VALUE', check: 'Text' },
    ],
    output: 'Text',
    colour: 65,
    tooltip: 'Eine Zeile mit Bezeichnung und Wert, z. B. Ort: Netto.',
  },
  {
    type: 'ha_entity_state',
    message0: 'Zustand von %1',
    args0: [{ type: 'field_entity', name: 'ENTITY_ID', value: '' }],
    output: 'Text',
    colour: 65,
    tooltip: 'Aktueller Zustand einer Entität, einsetzbar in Texten.',
  },
  {
    type: 'ha_entity_attribute',
    message0: 'Attribut %1 von %2',
    args0: [
      { type: 'field_input', name: 'ATTR', text: 'friendly_name' },
      { type: 'field_entity', name: 'ENTITY_ID', value: '' },
    ],
    output: 'Text',
    colour: 65,
    tooltip: 'Ein Attribut einer Entität, z. B. Preis oder Angebotszeitraum.',
  },
  {
    type: 'ha_variable_get',
    message0: 'Variable %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'zaehler' }],
    output: 'Text',
    colour: 30,
    tooltip: 'Wert einer Skript-Variable.',
  },
  {
    type: 'ha_if_present',
    message0: 'Anwesend: %1',
    args0: [{ type: 'field_entity', name: 'ENTITY_ID', value: '', domain: 'person,device_tracker,binary_sensor' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft, ob eine Person zu Hause ist oder ein Raum-Sensor anwesend/belegt meldet.',
  },
  {
    type: 'ha_if_zone',
    message0: 'Person %1 ist in Zone %2',
    args0: [
      { type: 'field_entity', name: 'ENTITY_ID', value: '', domain: 'person,device_tracker' },
      { type: 'field_entity', name: 'ZONE', value: '', domain: 'zone' },
    ],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Prüft, ob eine Person in einer Zone ist, z. B. Büro oder Zuhause.',
  },
  {
    type: 'ha_if_not_remembered',
    message0: 'Noch nicht gemeldet %1',
    args0: [{ type: 'input_value', name: 'VALUE', check: 'Text' }],
    message1: 'Speicher %1',
    args1: [{ type: 'field_entity', name: 'HELPER', value: '', domain: 'input_text' }],
    previousStatement: 'Condition',
    nextStatement: 'Condition',
    colour: 60,
    tooltip: 'Wahr, solange dieser Wert noch nicht im Hilfstext gespeichert ist. Danach „als gemeldet speichern“ verwenden.',
  },
  {
    type: 'ha_notify_telegram',
    message0: 'Telegram senden über %1',
    args0: [{ type: 'field_input', name: 'SERVICE', text: 'notify.telegram' }],
    message1: 'Titel (optional) %1',
    args1: [{ type: 'field_input', name: 'TITLE', text: '' }],
    message2: 'Nachricht %1',
    args2: [{ type: 'field_input', name: 'MESSAGE', text: '' }],
    message3: 'oder Textbaustein %1',
    args3: [{ type: 'input_value', name: 'MESSAGE_VALUE', check: 'Text' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 200,
    tooltip: 'Sendet eine Nachricht über die Telegram-Integration. Der Notify-Dienst muss in Home Assistant eingerichtet sein.',
  },
  {
    type: 'ha_alexa_speak',
    message0: 'Alexa %1 auf %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'SPEAK_TYPE',
        options: [
          ['spricht', 'tts'],
          ['kündigt an', 'announce'],
        ],
      },
      { type: 'field_entity', name: 'ENTITY_ID', value: '', domain: 'media_player' },
    ],
    message1: 'Nachricht %1',
    args1: [{ type: 'field_input', name: 'MESSAGE', text: '' }],
    message2: 'oder Textbaustein %1',
    args2: [{ type: 'input_value', name: 'MESSAGE_VALUE', check: 'Text' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 260,
    tooltip: 'Lässt Alexa sprechen oder ankündigen. Die Alexa-Media-Player-Integration muss installiert sein. Mit „Anwesend“ und „Noch nicht gemeldet“ nicht jedes Mal wiederholen.',
  },
  {
    type: 'ha_remember',
    message0: 'Als gemeldet speichern %1',
    args0: [{ type: 'input_value', name: 'VALUE', check: 'Text' }],
    message1: 'in Hilfstext %1',
    args1: [{ type: 'field_entity', name: 'HELPER', value: '', domain: 'input_text' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 30,
    tooltip: 'Speichert den Wert in einem input_text-Helfer, damit dieselbe Meldung nicht erneut kommt.',
  },
  {
    type: 'ha_delay',
    message0: 'Verzögerung %1',
    args0: [{ type: 'field_duration', name: 'DELAY_TIME', value: '00:00:30' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 200,
    tooltip: 'Wartet die angegebene Zeit.',
  },
  {
    type: 'ha_wait_for_state',
    message0: 'Warten bis %1 den Zustand %2 hat',
    args0: [
      { type: 'field_entity', name: 'ENTITY_ID', value: '' },
      { type: 'field_state', name: 'STATE', value: 'on' },
    ],
    message1: 'Timeout (optional) %1',
    args1: [{ type: 'field_duration', name: 'TIMEOUT', value: '' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 160,
    tooltip: 'Wartet auf einen bestimmten Zustand.',
  },
  {
    type: 'ha_wait_for_template',
    message0: 'Warten auf Template %1',
    args0: [{ type: 'field_input', name: 'TEMPLATE', text: "{{ is_state('light.wohnzimmer', 'on') }}" }],
    message1: 'Timeout (optional) %1',
    args1: [{ type: 'field_duration', name: 'TIMEOUT', value: '00:05:00' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 160,
    tooltip: 'Wartet, bis ein Template wahr wird.',
  },
  {
    type: 'ha_repeat',
    message0: 'Wiederholen %1 mal',
    args0: [{ type: 'field_number', name: 'COUNT', value: 5, min: 1 }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO', check: 'Action' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 200,
    tooltip: 'Wiederholt Aktionen n-mal.',
  },
  {
    type: 'ha_repeat_while',
    message0: 'Wiederholen solange %1',
    args0: [{ type: 'input_statement', name: 'WHILE', check: 'Condition' }],
    message1: 'führe aus %1',
    args1: [{ type: 'input_statement', name: 'DO', check: 'Action' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 210,
    tooltip: 'Wiederholt Aktionen, solange die Bedingung wahr ist.',
  },
  {
    type: 'ha_if_else',
    message0: 'wenn %1',
    args0: [{ type: 'input_statement', name: 'IF', check: 'Condition' }],
    message1: 'dann %1',
    args1: [{ type: 'input_statement', name: 'THEN', check: 'Action' }],
    message2: 'sonst %1',
    args2: [{ type: 'input_statement', name: 'ELSE', check: 'Action' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 210,
    tooltip: 'Bedingte Aktion mit optionalem Else-Zweig.',
  },
  {
    type: 'ha_stop',
    message0: 'Automatisierung stoppen %1',
    args0: [{ type: 'field_input', name: 'REASON', text: '' }],
    previousStatement: 'Action',
    colour: 160,
    tooltip: 'Beendet die aktuelle Automatisierung.',
  },
  {
    type: 'ha_light_on',
    message0: 'Schalte Licht ein %1',
    args0: [{ type: 'field_entity', name: 'ENTITY_ID', value: '', domain: 'light' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 40,
    tooltip: 'Schaltet ein Licht ein.',
  },
  {
    type: 'ha_light_off',
    message0: 'Schalte Licht aus %1',
    args0: [{ type: 'field_entity', name: 'ENTITY_ID', value: '', domain: 'light' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 40,
    tooltip: 'Schaltet ein Licht aus.',
  },
  {
    type: 'ha_switch_toggle',
    message0: 'Schalte Schalter um %1',
    args0: [{ type: 'field_entity', name: 'ENTITY_ID', value: '', domain: 'switch' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 40,
    tooltip: 'Schaltet einen Switch um.',
  },
  {
    type: 'ha_set_variable',
    message0: 'Variable setzen %1 = %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'zaehler' },
      { type: 'field_input', name: 'VALUE', text: '1' },
    ],
    message1: 'oder Textbaustein %1',
    args1: [{ type: 'input_value', name: 'VALUE_VALUE', check: 'Text' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 30,
    tooltip: 'Setzt eine Skript-Variable.',
  },
  {
    type: 'ha_send_push',
    message0: 'Push an %1: %2',
    args0: [
      { type: 'field_notify_target', name: 'NOTIFY_SERVICE', value: '' },
      { type: 'field_input', name: 'MESSAGE', text: 'Alarm ausgelöst!' },
    ],
    message1: 'oder Textbaustein %1',
    args1: [{ type: 'input_value', name: 'MESSAGE_VALUE', check: 'Text' }],
    previousStatement: 'Action',
    nextStatement: 'Action',
    colour: 290,
    tooltip: 'Sendet eine Push-Nachricht an ein Smartphone mit Companion App.',
  },
];
